/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file inputs.h
 *
 * @author Christopher A. Bohn
 *
 * @brief A function to configure interrupts, and a macro to debounce inputs
 *      generated by mechanical inputs.
 *
 ******************************************************************************/

/*
 * InterruptLab (c) 2021-24 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef INPUTS_H
#define INPUTS_H

#define DEBOUNCE_THRESHOLD (20)

#define debounce_interrupt(action)                            \
  do {                                                        \
    static unsigned long last_trigger = 0L;                   \
    unsigned long now = millis();                             \
    if (now - last_trigger > DEBOUNCE_THRESHOLD) { action; }  \
    last_trigger = now;                                       \
  } while(0)

#ifdef __cplusplus
extern "C" {
#endif

void initialize_interrupts(void);

#ifdef __cplusplus
} // extern "C"
#endif

#endif //INPUTS_H
