/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file outputs.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Functions to display the message editor's contents and to send the
 *      message to the host computer.
 *
 ******************************************************************************/

/*
 * InterruptLab (c) 2021-24 Christopher A. Bohn
 * Number Pad Texter (c) 2023-24 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef OUTPUTS_H
#define OUTPUTS_H

#ifdef __cplusplus
extern "C" {
#endif

void initialize_display(void);
void transmit_message(char message[], int8_t maximum_message_length);
void update_display(const char message[], int8_t cursor_position);

#ifdef __cplusplus
} // extern "C"
#endif

#endif //OUTPUTS_H
